# Generated by Django 3.0.6 on 2020-07-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200702_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='code',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
