# Generated by Django 3.0.6 on 2020-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200702_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
