# Generated by Django 3.0.6 on 2020-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_myblog_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='app1/gallery')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
