# Generated by Django 3.0.6 on 2020-07-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
